"""Ajout table UserAlbums

Revision ID: 4141eff65e96
Revises: b88ee7ab561d
Create Date: 2024-03-01 15:33:55.162876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4141eff65e96'
down_revision = 'b88ee7ab561d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_albums')
    # ### end Alembic commands ###
